### ISSUE TITLE
Fix a smart contract based on an audit

### ISSUE THREAD

**Issue by martdn** [streamity/stm-smartcontract#1]
**The contract code was checked for critical errors to lead to a loss of money by investors.**

The smart contracts were audited by [EthereumWorks](https://github.com/EthereumWorks) between 08 Dec 2017 and 10 Dec 2017.
Based on the [audit](https://github.com/EthereumWorks/stm-smartcontract/blob/master/audit/audit.md) of the smart contract, you @gfijrb need to make edits to the smart contract.

All comments including those not critical errors should be corrected.

**Comment by ghost** [comment]
Сorrected according to the comments of the [Audit](https://github.com/EthereumWorks/stm-smartcontract/blob/master/audit/audit.md)  in this comment [post audit](https://github.com/streamity/stm-smartcontract/tree/212600dc0a73f8cdd46ada64444ae7dde5bd9d20)

**Comment by martdn** [comment]
Fix tests of a contact #2
